version: '2.3'
services:
  app:
    build:
      context: ${PWD}
      dockerfile: Dockerfile
    environment:
      - DISPLAY_ERRORS=On
      - MYSQL_DATABASE
      - MYSQL_HOST
      - MYSQL_USER
      - MYSQL_PASSWORD
    volumes:
      - ${PWD}/index.php:/var/www/html/index.php
    ports:
      - 8000:80
    networks:
      - application
      - backend
    depends_on:
      - mysql

  mysql:
    image: mysql:5.7
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_PASSWORD}
    volumes:
      - ${PWD}/migrations:/docker-entrypoint-initdb.d
    networks:
      - backend
      - admin

  adminer:
    image: adminer
    ports:
      - 8080:8080
    networks:
      - admin
    depends_on:
      - mysql

networks:
  application:
  backend:
  admin: